import IntegerMultBounds.Networks.DisjointBalanced
import IntegerMultBounds.Networks.PairGrouping

/-! Executable weighted paired-exclusion recursion. Constructor order follows
`paired_exclusion_circuit.py`: balanced totals, coarse edges then weights,
recursive coarse outputs, strips, singles, within-group pairs, and cross-group
pairs with a shared left partial sum. Optional references represent zero.
Correctness and size properties are proved separately from these definitions. -/

namespace IntegerMultBounds.Networks.PairedCircuit

open DisjointCircuit DisjointBuilder

variable {ι : Type*} [DecidableEq ι]

abbrev WeightTable := List (ℕ × Ref)
abbrev EdgeTable := List ((ℕ × ℕ) × Ref)

/-- Python's insertion-ordered `combinations(points, 2)`. -/
def pairs : List ℕ → List (ℕ × ℕ)
  | [] => []
  | a :: rest => rest.map (a, ·) ++ pairs rest

/-- First matching association; missing graph terms have zero reference. -/
def lookup {K : Type*} [DecidableEq K] (table : List (K × Ref)) (key : K) : Ref :=
  ((table.find? (fun entry => entry.1 == key)).map Prod.snd).getD none

def edgeLookup (edges : EdgeTable) (a b : ℕ) : Ref :=
  lookup edges (min a b, max a b)

/-- Execute a list of stateful constructors strictly left to right. -/
def mapBuild {X Y : Type*} (f : List (Node ι) → X → List (Node ι) × Y)
    (nodes : List (Node ι)) : List X → List (Node ι) × List Y
  | [] => (nodes, [])
  | x :: xs =>
    let first := f nodes x
    let rest := mapBuild f first.1 xs
    (rest.1, first.2 :: rest.2)

omit [DecidableEq ι] in
theorem mapBuild_length {X Y : Type*} (f : List (Node ι) → X → List (Node ι) × Y)
    (nodes : List (Node ι)) (xs : List X) : (mapBuild f nodes xs).2.length = xs.length := by
  induction xs generalizing nodes with
  | nil => rfl
  | cons x xs ih => simp [mapBuild, ih]

omit [DecidableEq ι] in
/-- A pure key generated by each body is retained in exactly its input order. -/
theorem mapBuild_keys {X Y K : Type*} (f : List (Node ι) → X → List (Node ι) × Y)
    (key : Y → K) (expected : X → K)
    (h : ∀ ns x, key (f ns x).2 = expected x) (nodes : List (Node ι)) (xs : List X) :
    (mapBuild f nodes xs).2.map key = xs.map expected := by
  induction xs generalizing nodes with
  | nil => rfl
  | cons x xs ih => simp [mapBuild, h, ih]

@[simp] theorem lookup_nil {K : Type*} [DecidableEq K] (key : K) :
    lookup ([] : List (K × Ref)) key = none := rfl

@[simp] theorem lookup_cons_same {K : Type*} [DecidableEq K]
    (table : List (K × Ref)) (key : K) (r : Ref) : lookup ((key, r) :: table) key = r := by
  simp [lookup]

theorem lookup_cons_ne {K : Type*} [DecidableEq K]
    (table : List (K × Ref)) (key other : K) (r : Ref) (h : other ≠ key) :
    lookup ((other, r) :: table) key = lookup table key := by
  simp [lookup, h]

/-- Prefix construction starts with zero and finishes before the suffix pass. -/
def prefixBuild (nodes : List (Node ι)) (acc : Ref) : List Ref → List (Node ι) × List Ref
  | [] => (nodes, [acc])
  | x :: xs =>
    let next := smartAdd nodes acc x
    let rest := prefixBuild next.1 next.2 xs
    (rest.1, acc :: rest.2)

/-- Suffix construction performs additions from the last entry back to the first. -/
def suffixBuild (nodes : List (Node ι)) : List Ref → List (Node ι) × List Ref
  | [] => (nodes, [none])
  | x :: xs =>
    let rest := suffixBuild nodes xs
    let next := smartAdd rest.1 x (rest.2.headD none)
    (next.1, next.2 :: rest.2)

structure VectorResult (ι : Type*) where
  nodes : List (Node ι)
  total : Ref
  one : List Ref

/-- Literal `vector(values, False)`: prefix, suffix, then omissions in order. -/
def vectorFalse (nodes : List (Node ι)) (values : List Ref) : VectorResult ι :=
  let pre := prefixBuild nodes none values
  let suf := suffixBuild pre.1 values
  let outs := mapBuild (fun ns p => smartAdd ns p.1 p.2) suf.1 (pre.2.zip suf.2.tail)
  ⟨outs.1, pre.2.getLast?.getD none, outs.2⟩

theorem prefixBuild_length (nodes : List (Node ι)) (acc : Ref) (values : List Ref) :
    (prefixBuild nodes acc values).2.length = values.length + 1 := by
  induction values generalizing nodes acc with
  | nil => rfl
  | cons x xs ih => simp [prefixBuild, ih]

theorem suffixBuild_length (nodes : List (Node ι)) (values : List Ref) :
    (suffixBuild nodes values).2.length = values.length + 1 := by
  induction values with
  | nil => rfl
  | cons x xs ih => simp [suffixBuild, ih]

theorem vectorFalse_length (nodes : List (Node ι)) (values : List Ref) :
    (vectorFalse nodes values).one.length = values.length := by
  simp [vectorFalse, mapBuild_length, prefixBuild_length, suffixBuild_length]

structure BlockResult (ι : Type*) where
  nodes : List (Node ι)
  total : Ref
  one : WeightTable
  two : EdgeTable

/-- The actual ordered small-case query: surviving edges followed by weights. -/
def query (edges : EdgeTable) (weights : WeightTable) (excluded : List ℕ) : List Ref :=
  ((edges.filter (fun e => e.1.1 ∉ excluded ∧ e.1.2 ∉ excluded)).map Prod.snd) ++
    ((weights.filter (fun w => w.1 ∉ excluded)).map Prod.snd)

/-- The upstream branch used when there are at most four vertices. -/
def baseBlock (nodes : List (Node ι)) (points : List ℕ)
    (edges : EdgeTable) (weights : WeightTable) : BlockResult ι :=
  let total := DisjointBalanced.total nodes (query edges weights [])
  let one := mapBuild (fun ns a =>
    let result := DisjointBalanced.total ns (query edges weights [a])
    (result.1, (a, result.2))) total.1 points
  let two := mapBuild (fun ns p =>
    let result := DisjointBalanced.total ns (query edges weights [p.1, p.2])
    (result.1, (p, result.2))) one.1 (pairs points)
  ⟨two.1, total.2, one.2, two.2⟩

/-- Fine vertices in coarse group `i`, with total lookup for malformed inputs. -/
def groupAt (groups : List (List ℕ)) (i : ℕ) : List ℕ := groups[i]?.getD []

/-- Nested-loop edge references with left vertex varying most slowly. -/
def crossRefs (edges : EdgeTable) (left right : List ℕ) : List Ref :=
  left.flatMap fun a => right.map (edgeLookup edges a)

/-- Coarse edges are built before coarse vertex weights. -/
def coarseEdges (nodes : List (Node ι)) (groups : List (List ℕ)) (edges : EdgeTable) :
    List (Node ι) × EdgeTable :=
  mapBuild (fun ns p =>
    let result := DisjointBalanced.total ns (crossRefs edges (groupAt groups p.1) (groupAt groups p.2))
    (result.1, (p, result.2))) nodes (pairs (List.range groups.length))

def coarseWeights (nodes : List (Node ι)) (groups : List (List ℕ))
    (edges : EdgeTable) (weights : WeightTable) : List (Node ι) × WeightTable :=
  mapBuild (fun ns i =>
    let g := groupAt groups i
    let refs := g.map (lookup weights) ++ (pairs g).map (fun p => edgeLookup edges p.1 p.2)
    let result := DisjointBalanced.total ns refs
    (result.1, (i, result.2))) nodes (List.range groups.length)

/-- Flatten the upstream `for i,g in enumerate(groups): for a in g` order. -/
def members (groups : List (List ℕ)) : List (ℕ × ℕ) :=
  (List.range groups.length).flatMap fun i => (groupAt groups i).map (i, ·)

structure Strip where
  vertex : ℕ
  total : Ref
  outside : WeightTable

def stripLookup (strips : List Strip) (a : ℕ) : Strip :=
  (strips.find? (fun s => s.vertex == a)).getD ⟨a, none, []⟩

/-- One removed vertex: build its carry, each other-group value, then the
shared prefix/suffix vector. Its omissions are keyed by the other groups. -/
def buildStrip (nodes : List (Node ι)) (groups : List (List ℕ))
    (edges : EdgeTable) (weights : WeightTable) (ia : ℕ × ℕ) : List (Node ι) × Strip :=
  let remaining := (groupAt groups ia.1).filter (· != ia.2)
  let other := (List.range groups.length).filter (· != ia.1)
  let carry := DisjointBalanced.total nodes (remaining.map (lookup weights))
  let vals := mapBuild (fun ns j =>
    DisjointBalanced.total ns (crossRefs edges remaining (groupAt groups j))) carry.1 other
  let vec := vectorFalse vals.1 (carry.2 :: vals.2)
  (vec.nodes, ⟨ia.2, vec.total, other.zip vec.one.tail⟩)

def buildStrips (nodes : List (Node ι)) (groups : List (List ℕ))
    (edges : EdgeTable) (weights : WeightTable) : List (Node ι) × List Strip :=
  mapBuild (fun ns ia => buildStrip ns groups edges weights ia) nodes (members groups)

def buildSingles (nodes : List (Node ι)) (groups : List (List ℕ))
    (outside : WeightTable) (strips : List Strip) : List (Node ι) × WeightTable :=
  mapBuild (fun ns ia =>
    let result := smartAdd ns (lookup outside ia.1) (stripLookup strips ia.2).total
    (result.1, (ia.2, result.2))) nodes (members groups)

/-- Within-group pair outputs reuse the corresponding coarse outside sum. -/
def internalPairs (groups : List (List ℕ)) (outside : WeightTable) : EdgeTable :=
  (List.range groups.length).flatMap fun i =>
    (pairs (groupAt groups i)).map (fun p => (p, lookup outside i))

/-- For a fixed cross-group left vertex, allocate `left` once, then share it
through the entire inner right-vertex loop, matching Python evaluation order. -/
def buildCrossLeft (nodes : List (Node ι)) (groups : List (List ℕ))
    (edges : EdgeTable) (far : EdgeTable) (strips : List Strip) (ij : ℕ × ℕ) (a : ℕ) :
    List (Node ι) × EdgeTable :=
  let left := smartAdd nodes (lookup far ij) (lookup (stripLookup strips a).outside ij.2)
  mapBuild (fun ns b =>
    let cross := DisjointBalanced.total ns (crossRefs edges
      ((groupAt groups ij.1).filter (· != a)) ((groupAt groups ij.2).filter (· != b)))
    let right := smartAdd cross.1 (lookup (stripLookup strips b).outside ij.1) cross.2
    let result := smartAdd right.1 left.2 right.2
    (result.1, ((a, b), result.2))) left.1 (groupAt groups ij.2)

def buildCrossGroup (nodes : List (Node ι)) (groups : List (List ℕ))
    (edges : EdgeTable) (far : EdgeTable) (strips : List Strip) (ij : ℕ × ℕ) :
    List (Node ι) × EdgeTable :=
  let result := mapBuild (fun ns a => buildCrossLeft ns groups edges far strips ij a)
    nodes (groupAt groups ij.1)
  (result.1, result.2.flatten)

def buildCrossPairs (nodes : List (Node ι)) (groups : List (List ℕ))
    (edges : EdgeTable) (far : EdgeTable) (strips : List Strip) : List (Node ι) × EdgeTable :=
  let result := mapBuild (fun ns ij => buildCrossGroup ns groups edges far strips ij)
    nodes (pairs (List.range groups.length))
  (result.1, result.2.flatten)

/-- Finish a level after the recursive coarse call, retaining its total. -/
def reconstruct (groups : List (List ℕ)) (edges : EdgeTable) (weights : WeightTable)
    (coarse : BlockResult ι) : BlockResult ι :=
  let strips := buildStrips coarse.nodes groups edges weights
  let single := buildSingles strips.1 groups coarse.one strips.2
  let cross := buildCrossPairs single.1 groups edges coarse.two strips.2
  ⟨cross.1, coarse.total, single.2, internalPairs groups coarse.one ++ cross.2⟩

/-- The complete weighted paired-exclusion algorithm with strict coarse-size
recursion. No supplied checker result is used to select or build its nodes. -/
def block (nodes : List (Node ι)) (points : List ℕ)
    (edges : EdgeTable) (weights : WeightTable) : BlockResult ι :=
  if points.length ≤ 4 then baseBlock nodes points edges weights else
    let groups := PairGrouping.groups points
    let ce := coarseEdges nodes groups edges
    let cw := coarseWeights ce.1 groups edges weights
    let coarse := block cw.1 (List.range groups.length) ce.2 cw.2
    reconstruct groups edges weights coarse
termination_by points.length
decreasing_by
  simp only [List.length_range]
  exact PairGrouping.length_groups_lt points (by omega)

/-- Computation equation for the complete small branch. -/
theorem block_small (nodes : List (Node ι)) (points : List ℕ)
    (edges : EdgeTable) (weights : WeightTable) (h : points.length ≤ 4) :
    block nodes points edges weights = baseBlock nodes points edges weights := by
  rw [block, ite_eq_left h]

/-- Computation equation exposing the exact coarse call and reconstruction. -/
theorem block_large (nodes : List (Node ι)) (points : List ℕ)
    (edges : EdgeTable) (weights : WeightTable) (h : 4 < points.length) :
    block nodes points edges weights =
      let groups := PairGrouping.groups points
      let ce := coarseEdges nodes groups edges
      let cw := coarseWeights ce.1 groups edges weights
      reconstruct groups edges weights (block cw.1 (List.range groups.length) ce.2 cw.2) := by
  rw [block, ite_eq_right (by omega)]

end IntegerMultBounds.Networks.PairedCircuit
