import IntegerMultBounds.Networks.Labels

/-! Nondegenerate source labels for shared-point triple families. The labels
are the actual spans of supported indicator vectors, not chosen abstract
nondegenerate subspaces. The argument works even when the ambient rational
form is degenerate (ambient dimension nine). -/

namespace IntegerMultBounds.Networks.SharedPointLabels

open Labels

variable {h : ℕ}

/-- Source labels are generated by precisely the supported triple indicators.
A set-valued support also covers arbitrary finite indexed source families. -/
def sourceSpan (support : Set (Finset (Fin h))) : Submodule ℚ (Fin h → ℚ) :=
  Submodule.span ℚ ((fun S => (indicator S : Fin h → ℚ)) '' support)

/-- Enlarging the actual source support enlarges its generated label space. -/
theorem sourceSpan_mono {support larger : Set (Finset (Fin h))} (hs : support ⊆ larger) :
    sourceSpan support ≤ sourceSpan larger :=
  Submodule.span_mono (Set.image_mono hs)

theorem indicator_mem_sourceSpan {support : Set (Finset (Fin h))} {S : Finset (Fin h)}
    (hS : S ∈ support) : (indicator S : Fin h → ℚ) ∈ sourceSpan support :=
  Submodule.subset_span ⟨S, hS, rfl⟩

/-- Every shared-point triple has coordinate sum three times its common entry. -/
def sharedPlane (common : Fin h) : Submodule ℚ (Fin h → ℚ) where
  carrier := {x | (∑ i, x i) = 3 * x common}
  zero_mem' := by simp
  add_mem' := by
    intro x y hx hy
    simp only [Set.mem_ofPred_eq, Pi.add_apply, Finset.sum_add_distrib] at hx hy ⊢
    rw [hx, hy]
    ring
  smul_mem' := by
    intro c x hx
    simp only [Set.mem_ofPred_eq, Pi.smul_apply, smul_eq_mul, ← Finset.mul_sum] at hx ⊢
    rw [hx]
    ring

@[simp] theorem mem_sharedPlane (common : Fin h) (x : Fin h → ℚ) :
    x ∈ sharedPlane common ↔ (∑ i, x i) = 3 * x common := Iff.rfl

theorem sourceSpan_le_sharedPlane (common : Fin h) (support : Set (Finset (Fin h)))
    (htriples : ∀ S ∈ support, S.card = 3)
    (hcommon : ∀ S ∈ support, common ∈ S) :
    sourceSpan support ≤ sharedPlane common := by
  apply Submodule.span_le.mpr
  rintro x ⟨S, hS, rfl⟩
  simp [mem_sharedPlane, htriples S hS, indicator, hcommon S hS]

/-- The negative rank-one correction cancels exactly the common coordinate. -/
theorem quadratic_eq (common : Fin h) (x : Fin h → ℚ) (hx : x ∈ sharedPlane common) :
    rational h x x = ∑ i ∈ Finset.univ.erase common, (x i) ^ 2 := by
  have hs : (∑ i, x i) = 3 * x common := hx
  have ht := Finset.sum_erase_add (Finset.univ : Finset (Fin h))
    (fun i => (x i) ^ 2) (Finset.mem_univ common)
  simp only [rational, form_apply, hs, ← pow_two]
  nlinarith

theorem quadratic_nonneg (common : Fin h) (x : Fin h → ℚ) (hx : x ∈ sharedPlane common) :
    0 ≤ rational h x x := by
  rw [quadratic_eq common x hx]
  exact Finset.sum_nonneg (fun i _ => sq_nonneg (x i))

/-- Vanishing of the outside squares forces the whole vector to vanish:
the shared-point linear relation also kills its common coordinate. -/
theorem quadratic_eq_zero (common : Fin h) (x : Fin h → ℚ) (hx : x ∈ sharedPlane common)
    (hz : rational h x x = 0) : x = 0 := by
  have hs : (∑ i, x i) = 3 * x common := hx
  rw [quadratic_eq common x hx] at hz
  have hout (i : Fin h) (hi : i ≠ common) : x i = 0 := by
    have hle := Finset.single_le_sum (fun j (_ : j ∈ Finset.univ.erase common) => sq_nonneg (x j))
      (show i ∈ Finset.univ.erase common by simp [hi])
    nlinarith [sq_nonneg (x i)]
  have hsum : (∑ i, x i) = x common := by
    apply Finset.sum_eq_single common
    · intro i _ hi
      exact hout i hi
    · simp
  rw [hsum] at hs
  have hc : x common = 0 := by linarith
  funext i
  by_cases hi : i = common
  · subst i; exact hc
  · exact hout i hi

/-- The restricted form is positive definite on the entire shared-point plane. -/
theorem quadratic_pos (common : Fin h) (x : Fin h → ℚ) (hx : x ∈ sharedPlane common)
    (hne : x ≠ 0) : 0 < rational h x x := by
  have hn := quadratic_nonneg common x hx
  have hz : rational h x x ≠ 0 := fun hh => hne (quadratic_eq_zero common x hx hh)
  exact lt_of_le_of_ne hn (Ne.symm hz)

/-- Any actual subspace of this plane inherits nondegeneracy. -/
theorem subspace_nondegenerate (common : Fin h) (W : Submodule ℚ (Fin h → ℚ))
    (hW : W ≤ sharedPlane common) : ((rational h).restrict W).Nondegenerate := by
  constructor
  · intro x hx
    apply Subtype.ext
    exact quadratic_eq_zero common x (hW x.property) (hx x)
  · intro x hx
    apply Subtype.ext
    exact quadratic_eq_zero common x (hW x.property) (hx x)

/-- The concrete shared-point triple source span is nondegenerate, with only
combinatorial hypotheses on its generators. No ambient dimension exclusion
or externally supplied positivity or nondegeneracy premise is needed. -/
theorem sourceSpan_nondegenerate (common : Fin h) (support : Set (Finset (Fin h)))
    (htriples : ∀ S ∈ support, S.card = 3)
    (hcommon : ∀ S ∈ support, common ∈ S) :
    ((rational h).restrict (sourceSpan support)).Nondegenerate :=
  subspace_nondegenerate common _ (sourceSpan_le_sharedPlane common support htriples hcommon)

/-- A finite indexed source family induces exactly its supported source span. -/
def indexedSpan {ι : Type*} (triples : ι → Finset (Fin h)) (support : Set ι) :
    Submodule ℚ (Fin h → ℚ) := sourceSpan (triples '' support)

theorem indexedSpan_mono {ι : Type*} (triples : ι → Finset (Fin h))
    {support larger : Set ι} (hs : support ⊆ larger) :
    indexedSpan triples support ≤ indexedSpan triples larger :=
  sourceSpan_mono (Set.image_mono hs)

theorem indexedSpan_nondegenerate {ι : Type*} (common : Fin h)
    (triples : ι → Finset (Fin h)) (support : Set ι)
    (htriples : ∀ i ∈ support, (triples i).card = 3)
    (hcommon : ∀ i ∈ support, common ∈ triples i) :
    ((rational h).restrict (indexedSpan triples support)).Nondegenerate := by
  apply sourceSpan_nondegenerate common
  · rintro S ⟨i, hi, rfl⟩
    exact htriples i hi
  · rintro S ⟨i, hi, rfl⟩
    exact hcommon i hi

end IntegerMultBounds.Networks.SharedPointLabels
