import IntegerMultBounds.Networks.DAGSupportTrace
import IntegerMultBounds.Networks.SharedPointOutputIndex
import IntegerMultBounds.Networks.SharedPointOutputLabels

/-! Actual forward source-span labels for the globally interned fifty-copy
circuit. Node common-point properties, increasing edges, zero loss, and terminal
partial-output labels are proved from the constructed DAG. Sink attachment,
inverse schedules, and global rank assembly remain separate. -/

namespace IntegerMultBounds.Networks.Shared50Frames

open DisjointCircuit NeighborCounts SharedPointReplay

attribute [local irreducible] SharedPointReplay.circuit Paired49Certificate.nodes
  Certificates.Paired49.entries Certificates.Paired49.outputs Certificates.Paired49.bank

/-- Every actual global node has triple sources with a common point. Input
nodes follow from structural validity; additions follow from replay provenance. -/
theorem node_common (node : Node (Triple 50)) (hn : node ∈ circuit.nodes) :
    ∃ common : Fin 50, ∀ T ∈ node.support, T.val.card = 3 ∧ common ∈ T.val := by
  cases hk : node.kind with
  | input source =>
    obtain ⟨i, hi, he⟩ := List.mem_iff_getElem.mp hn
    have hv := DAGValueTransfer.validFrom_get [] circuit.nodes valid i hi
    rw [he] at hv
    have hs : node.support = {source} := by simpa only [Node.Valid,hk] using hv
    obtain ⟨common,hcommon⟩ := Finset.card_pos.mp (show 0 < source.val.card by rw [source.property]; omega)
    refine ⟨common, ?_⟩
    intro T hT
    have hT' : T = source := by simpa only [hs,Finset.mem_singleton] using hT
    subst T
    exact ⟨source.property,hcommon⟩
  | add left right =>
    have hm := contained node.support ⟨node,hn,⟨left,right,hk⟩,rfl⟩
    obtain ⟨copy,hcopy,hs⟩ := Finset.mem_image.mp hm
    refine ⟨copy.1, ?_⟩
    intro T hT
    exact ⟨T.property, SharedPointFamily.support_common copy hcopy T (hs ▸ hT)⟩

/-- The event list is generated by the actual allocator on actual output refs. -/
def events : List (DAGSupportTrace.Event (Triple 50)) := DAGSupportTrace.events circuit.nodes outputRefs

def initialSupports : ℕ → Finset (Triple 50) := DAGSupportTrace.initialSupports circuit.nodes outputRefs

def initialLabels : ℕ → Submodule ℚ (Fin 50 → ℚ) :=
  fun i => FanoutFrames.label (fun T : Triple 50 => T.val) (initialSupports i)

def updates : List (ℕ × Submodule ℚ (Fin 50 → ℚ)) :=
  DAGSupportTrace.updates events (fun T : Triple 50 => T.val)

def finalLabels : ℕ → Submodule ℚ (Fin 50 → ℚ) := RankTrace.finish initialLabels updates

/-- Erasing the actual support labels gives exactly the actual allocated gates. -/
theorem events_erasure : events.map DAGSupportTrace.Event.gate = SharedPointExecution.code.gates :=
  DAGSupportTrace.events_erasure circuit.nodes outputRefs

theorem ready : DAGSupportTrace.TraceReady events initialSupports :=
  (DAGSupportTrace.events_ready circuit.nodes outputRefs valid outputRefs_bounds).1

/-- Every actual forward frame edge increases its source-span label. -/
theorem increasing : ∀ p ∈ RankTrace.edges initialLabels updates, p.1 ≤ p.2 :=
  DAGSupportTrace.events_increasing circuit.nodes outputRefs valid outputRefs_bounds _

/-- The actual forward trace has no dimension decrease. -/
theorem loss_zero :
    RankTrace.loss (fun U : Submodule ℚ (Fin 50 → ℚ) => Module.finrank ℚ U) initialLabels updates = 0 :=
  DAGSupportTrace.events_loss_zero circuit.nodes outputRefs valid outputRefs_bounds _

/-- Both endpoints of every actual forward frame edge are nondegenerate for
the corrected rational form. No assumed frame-label conditions remain. -/
theorem nondegenerate : ∀ p ∈ RankTrace.edges initialLabels updates,
    ((Labels.rational 50).restrict p.1).Nondegenerate ∧
      ((Labels.rational 50).restrict p.2).Nondegenerate :=
  DAGSupportTrace.events_nondegenerate circuit.nodes outputRefs valid outputRefs_bounds _ node_common

/-- The final support at each physical output is its actual lifted exclusion. -/
theorem final_support (i : ℕ) (hi : i < circuit.outputs.length) :
    DAGSupportTrace.run events initialSupports (SharedPointExecution.code.outputSlot i) =
      expected circuit.outputs[i] := by
  have hi' : i < outputRefs.length := by simpa only [outputRefs,List.length_map] using hi
  have hb := output_bound circuit.outputs[i] (List.getElem_mem hi)
  have hs := SharedPointReplay.output_support circuit.outputs[i] (List.getElem_mem hi)
  simp only [CorrectOutput,List.getElem?_map,List.getElem?_eq_getElem hb,Option.map_some] at hs
  have hr := DAGSupportTrace.output_support circuit.nodes outputRefs valid outputRefs_bounds i hi'
  simp only [outputRefs,List.getElem_map] at hr
  rw [DAGSupportTrace.nodeSupport_get circuit.nodes _ hb] at hr
  exact hr.trans (Option.some.inj hs)

theorem final_label_expected (i : ℕ) (hi : i < circuit.outputs.length) :
    finalLabels (SharedPointExecution.code.outputSlot i) =
      FanoutFrames.label (fun T : Triple 50 => T.val) (expected circuit.outputs[i]) := by
  have hh := congrFun (DAGSupportTrace.run_labels events (fun T : Triple 50 => T.val) initialSupports)
    (SharedPointExecution.code.outputSlot i)
  change FanoutFrames.label (fun T : Triple 50 => T.val)
    (DAGSupportTrace.run events initialSupports (SharedPointExecution.code.outputSlot i)) =
    finalLabels (SharedPointExecution.code.outputSlot i) at hh
  rw [final_support i hi] at hh
  exact hh.symm

/-- At each arithmetic common-point/pair address, the actual final physical
label is exactly the existing rational partial-output source span. -/
theorem final_label (c : Fin 50) (j : Fin 1176) :
    finalLabels (SharedPointExecution.code.outputSlot (SharedPointOutputIndex.index c j)) =
      SharedPointMap.outputSpan c (embedding c j) := by
  rw [final_label_expected _ (SharedPointOutputIndex.index_output_bound c j)]
  have hk := SharedPointOutputIndex.output_key c j
  have hc := congrArg Prod.fst hk
  have hp := congrArg Prod.snd hk
  simp only [key] at hc hp
  rw [expected,hc,hp]
  exact SharedPointOutputLabels.exclusion_label 49 c j

/-- The actual physical output labels are nondegenerate, including outputs
whose scalar identity node has no elementary instructions. -/
theorem final_nondegenerate (c : Fin 50) (j : Fin 1176) :
    ((Labels.rational 50).restrict
      (finalLabels (SharedPointExecution.code.outputSlot (SharedPointOutputIndex.index c j)))).Nondegenerate := by
  rw [final_label]
  exact SharedPointMap.outputSpan_nondegenerate c (embedding c j)

/-- The proved output label is contained in the target line's orthogonal
complement, supplying the exact forward endpoint inclusion for attachment. -/
theorem final_orthogonal (c : Fin 50) (j : Fin 1176) :
    finalLabels (SharedPointExecution.code.outputSlot (SharedPointOutputIndex.index c j)) ≤
      (Labels.rational 50).orthogonal (ℚ ∙ (Labels.indicator (embedding c j).val : Fin 50 → ℚ)) := by
  rw [final_label]
  have hh := SharedPointOutputLabels.exclusion_orthogonal 49 c j
  rw [SharedPointOutputLabels.exclusion_label 49 c j] at hh
  exact hh

end IntegerMultBounds.Networks.Shared50Frames
