import IntegerMultBounds.Machine.BinaryDescriptorDifference
import IntegerMultBounds.Machine.PlacedDescriptorConstruction
import IntegerMultBounds.Machine.ArbitraryWidthHighMetadataBudget

/-! High-field views are constructed from sole original P,G,B,e,rho headers.
The literal low width, high/low radix ranges and the three movement dimensions
are generated by actual subtraction, powers and products on seventeen tapes. -/
namespace IntegerMultBounds.Machine.ArbitraryWidthHighDimensions
noncomputable section
variable {a : ℕ}
open SharedPlacementAlphabet (setTape)

private def hd : Option (List Bool) → ℤ | none => 0 | some _ => 1
private def tp : Option (List Bool) → ℤ → Fin (a+4)
  | none => fun _ => blank
  | some bs => RadixZeroFill.encodedBinary bs

def bank (hs : Fin 5 → List Bool) (ds : Fin 6 → Option (List Bool)) : Tapes 17 a :=
  ⟨fun i => if i.val < 5 then 1 else
      if h : i.val < 11 then hd (ds ⟨i.val-5,by omega⟩) else 0,
    fun i => if h : i.val < 5 then RadixZeroFill.encodedBinary (hs ⟨i.val,h⟩) else
      if h' : i.val < 11 then tp (ds ⟨i.val-5,by omega⟩) else fun _ => blank⟩

def words (q P G B e r : ℕ) : Fin 6 → List Bool :=
  ![RecursiveChildQuotientsConstant.bits (e-r),FixedBasePowerStep.bits q r,
    FixedBasePowerStep.bits q (e-r),BoundedProductDescriptor.bits P (q^r),
    BoundedProductDescriptor.bits G (q^(e-r)),BoundedProductDescriptor.bits B (q^(e-r))]

def values (q P G B e r : ℕ) : Fin 6 → ℕ := ![e-r,q^r,q^(e-r),P*q^r,G*q^(e-r),B*q^(e-r)]
def originalValues (P G B e r : ℕ) : Fin 5 → ℕ := ![P,G,B,e,r]

def state (q P G B e r stage : ℕ) (hs : Fin 5 → List Bool) : Tapes 17 a :=
  bank hs (fun i => if i.val < stage then some (words q P G B e r i) else none)
def input (hs : Fin 5 → List Bool) := bank (a := a) hs (fun _ => none)
def output (q P G B e r : ℕ) (hs : Fin 5 → List Bool) := state (a := a) q P G B e r 6 hs

private theorem encoded_binary (bs : List Bool) : RadixZeroFill.encodedBinary (q := a) bs =
    CountedLoopReuseAlphabet.binary bs := by
  change (fun z => (RadixToBinary.binaryEncoding (q := a)).encode (CountedCopyReuse.binary bs z)) = _
  exact CountedLoopReuseAlphabet.encoding_binary bs
private theorem encoded_descriptor (bs : List Bool) : RadixZeroFill.encodedBinary (q := a) bs =
    BinaryDescriptorStack.descriptor bs := (BinaryDescriptorStackRoundtrip.descriptor_encoded _).symm

private theorem binary_descriptor (bs : List Bool) :
    CountedLoopReuseAlphabet.binary (a := a) bs = BinaryDescriptorStack.descriptor bs :=
  (encoded_binary bs).symm.trans (encoded_descriptor bs)

private theorem placed_exact {s u t z cost : ℕ} {M : Program s z a}
    (e : Fin (s+u) ≃ Fin t) (v w : Tapes t a) (small small' : Tapes s a)
    (ha : Placement.active e v = small) (hf : Placement.active e w = small')
    (he : Placement.extra e v = Placement.extra e w)
    (h : HoareTime M (fun x => x = small) (fun x => x = small') cost) :
    HoareTime (Placement.placed M e) (fun x => x = v) (fun x => x = w) cost := by
  apply (Placement.hoare_at h e v ha).consequence (fun _ h => h) _ le_rfl
  rintro x ⟨y,rfl,rfl⟩
  rw [Placement.replace,he,← hf]
  exact Placement.view _ _

def differencePlacement : Fin (3+14) ≃ Fin 17 where
  toFun := ![3,4,5,0,1,2,6,7,8,9,10,11,12,13,14,15,16]
  invFun := ![3,4,5,0,1,2,6,7,8,9,10,11,12,13,14,15,16]
  left_inv i := by fin_cases i <;> rfl
  right_inv i := by fin_cases i <;> rfl
def differenceProgram := Placement.placed (BinaryDescriptorDifference.program (a := a)) differencePlacement

def highPlacement : Fin (8+9) ≃ Fin 17 where
  toFun := ![11,12,13,14,15,6,16,4,0,1,2,3,5,7,8,9,10]
  invFun := ![8,9,10,11,7,12,5,13,14,15,16,0,1,2,3,4,6]
  left_inv i := by fin_cases i <;> rfl
  right_inv i := by fin_cases i <;> rfl
def highProgram (q : ℕ) := Placement.placed (FixedBasePowerDescriptor.program (q := a) q) highPlacement

def lowPlacement : Fin (8+9) ≃ Fin 17 where
  toFun := ![11,12,13,14,15,7,16,5,0,1,2,3,4,6,8,9,10]
  invFun := ![8,9,10,11,12,7,13,5,14,15,16,0,1,2,3,4,6]
  left_inv i := by fin_cases i <;> rfl
  right_inv i := by fin_cases i <;> rfl
def lowProgram (q : ℕ) := Placement.placed (FixedBasePowerDescriptor.program (q := a) q) lowPlacement

def prefixPlacement : Fin (6+11) ≃ Fin 17 where
  toFun := ![11,8,12,6,13,0,1,2,3,4,5,7,9,10,14,15,16]
  invFun := ![5,6,7,8,9,10,3,11,1,12,13,0,2,4,14,15,16]
  left_inv i := by fin_cases i <;> rfl
  right_inv i := by fin_cases i <;> rfl
def prefixProgram := Placement.placed (BoundedProductDescriptor.program (q := a)) prefixPlacement

def gapPlacement : Fin (6+11) ≃ Fin 17 where
  toFun := ![11,9,12,7,13,1,0,2,3,4,5,6,8,10,14,15,16]
  invFun := ![6,5,7,8,9,10,11,3,12,1,13,0,2,4,14,15,16]
  left_inv i := by fin_cases i <;> rfl
  right_inv i := by fin_cases i <;> rfl
def gapProgram := Placement.placed (BoundedProductDescriptor.program (q := a)) gapPlacement

def suffixPlacement : Fin (6+11) ≃ Fin 17 where
  toFun := ![11,10,12,7,13,2,0,1,3,4,5,6,8,9,14,15,16]
  invFun := ![6,7,5,8,9,10,11,3,12,13,1,0,2,4,14,15,16]
  left_inv i := by fin_cases i <;> rfl
  right_inv i := by fin_cases i <;> rfl
def suffixProgram := Placement.placed (BoundedProductDescriptor.program (q := a)) suffixPlacement

def program (q : ℕ) := seq (seq (seq (seq (seq (differenceProgram (a := a)) (highProgram q))
  (lowProgram q)) prefixProgram) gapProgram) suffixProgram

theorem words_value (q P G B e r : ℕ) (i : Fin 6) :
    Counter.value (words q P G B e r i) = values q P G B e r i := by
  fin_cases i <;> simp [words,values,RecursiveChildQuotientsConstant.bits_value,
    FixedBasePowerStep.bits_value,BoundedProductDescriptor.bits_value]

theorem words_canonical (q P G B e r : ℕ) (i : Fin 6) :
    GrowingCounterData.Canonical (words q P G B e r i) := by
  fin_cases i
  · exact RecursiveChildQuotientsConstant.bits_canonical _
  · exact FixedBasePowerStep.bits_canonical _ _
  · exact FixedBasePowerStep.bits_canonical _ _
  · exact BoundedProductDescriptor.bits_canonical _ _
  · exact BoundedProductDescriptor.bits_canonical _ _
  · exact BoundedProductDescriptor.bits_canonical _ _

private theorem difference_active_input (_q _P _G _B _e _r : ℕ) (hs : Fin 5 → List Bool) :
    Placement.active differencePlacement (input (a := a) hs) = BinaryDescriptorDifference.input (a := a) (hs 3) (hs 4) := by
  apply congrArg₂ Tapes.mk
  · funext i; fin_cases i <;> rfl
  · funext i; fin_cases i
    · exact encoded_binary (hs 3)
    · exact encoded_binary (hs 4)
    · rfl

private theorem difference_active_output (q P G B e r : ℕ) (hs : Fin 5 → List Bool) :
    Placement.active differencePlacement (state (a := a) q P G B e r 1 hs) = BinaryDescriptorDifference.output (a := a) (hs 3) (hs 4) (RecursiveChildQuotientsConstant.bits (e-r)) := by
  apply congrArg₂ Tapes.mk
  · funext i; fin_cases i <;> rfl
  · funext i; fin_cases i
    · exact encoded_binary (hs 3)
    · exact encoded_binary (hs 4)
    · exact encoded_descriptor (RecursiveChildQuotientsConstant.bits (e-r))

private theorem difference_extra (q P G B e r : ℕ) (hs : Fin 5 → List Bool) :
    Placement.extra differencePlacement (input (a := a) hs) = Placement.extra differencePlacement (state (a := a) q P G B e r 1 hs) := by
  apply congrArg₂ Tapes.mk <;> funext i <;> fin_cases i <;> rfl

private theorem high_active_input (q P G B e r : ℕ) (hs : Fin 5 → List Bool) :
    Placement.active highPlacement (state (a := a) q P G B e r 1 hs) = FixedBasePowerDescriptor.input (q := a) (hs 4) := by
  apply congrArg₂ Tapes.mk
  · funext i; fin_cases i <;> rfl
  · funext i; fin_cases i
    · rfl
    · rfl
    · rfl
    · rfl
    · rfl
    · rfl
    · rfl
    · exact encoded_binary (hs 4)

private theorem high_active_output (q P G B e r : ℕ) (hs : Fin 5 → List Bool) :
    Placement.active highPlacement (state (a := a) q P G B e r 2 hs) = FixedBasePowerDescriptor.output (q := a) q r (hs 4) := by
  apply congrArg₂ Tapes.mk
  · funext i; fin_cases i <;> rfl
  · funext i; fin_cases i
    · rfl
    · rfl
    · rfl
    · rfl
    · rfl
    · rfl
    · rfl
    · exact encoded_binary (hs 4)

private theorem high_extra (q P G B e r : ℕ) (hs : Fin 5 → List Bool) :
    Placement.extra highPlacement (state (a := a) q P G B e r 1 hs) = Placement.extra highPlacement (state (a := a) q P G B e r 2 hs) := by
  apply congrArg₂ Tapes.mk <;> funext i <;> fin_cases i <;> rfl

private theorem low_active_input (q P G B e r : ℕ) (hs : Fin 5 → List Bool) :
    Placement.active lowPlacement (state (a := a) q P G B e r 2 hs) = FixedBasePowerDescriptor.input (q := a) (RecursiveChildQuotientsConstant.bits (e-r)) := by
  apply congrArg₂ Tapes.mk
  · funext i; fin_cases i <;> rfl
  · funext i; fin_cases i
    · rfl
    · rfl
    · rfl
    · rfl
    · rfl
    · rfl
    · rfl
    · exact encoded_binary (RecursiveChildQuotientsConstant.bits (e-r))

private theorem low_active_output (q P G B e r : ℕ) (hs : Fin 5 → List Bool) :
    Placement.active lowPlacement (state (a := a) q P G B e r 3 hs) = FixedBasePowerDescriptor.output (q := a) q (e-r) (RecursiveChildQuotientsConstant.bits (e-r)) := by
  apply congrArg₂ Tapes.mk
  · funext i; fin_cases i <;> rfl
  · funext i; fin_cases i
    · rfl
    · rfl
    · rfl
    · rfl
    · rfl
    · rfl
    · rfl
    · exact encoded_binary (RecursiveChildQuotientsConstant.bits (e-r))

private theorem low_extra (q P G B e r : ℕ) (hs : Fin 5 → List Bool) :
    Placement.extra lowPlacement (state (a := a) q P G B e r 2 hs) = Placement.extra lowPlacement (state (a := a) q P G B e r 3 hs) := by
  apply congrArg₂ Tapes.mk <;> funext i <;> fin_cases i <;> rfl

private theorem prefix_active_input (q P G B e r : ℕ) (hs : Fin 5 → List Bool) :
    Placement.active prefixPlacement (state (a := a) q P G B e r 3 hs) = BoundedProductDescriptor.input (q := a) (FixedBasePowerStep.bits q r) (hs 0) := by
  apply congrArg₂ Tapes.mk
  · funext i; fin_cases i <;> rfl
  · funext i; fin_cases i
    · rfl
    · rfl
    · rfl
    · rfl
    · rfl
    · rfl

private theorem prefix_active_output (q P G B e r : ℕ) (hs : Fin 5 → List Bool) :
    Placement.active prefixPlacement (state (a := a) q P G B e r 4 hs) = BoundedProductDescriptor.output (q := a) (FixedBasePowerStep.bits q r) (hs 0) P (q^r) := by
  apply congrArg₂ Tapes.mk
  · funext i; fin_cases i <;> rfl
  · funext i; fin_cases i
    · rfl
    · rfl
    · rfl
    · rfl
    · rfl
    · rfl

private theorem prefix_extra (q P G B e r : ℕ) (hs : Fin 5 → List Bool) :
    Placement.extra prefixPlacement (state (a := a) q P G B e r 3 hs) = Placement.extra prefixPlacement (state (a := a) q P G B e r 4 hs) := by
  apply congrArg₂ Tapes.mk <;> funext i <;> fin_cases i <;> rfl

private theorem gap_active_input (q P G B e r : ℕ) (hs : Fin 5 → List Bool) :
    Placement.active gapPlacement (state (a := a) q P G B e r 4 hs) = BoundedProductDescriptor.input (q := a) (FixedBasePowerStep.bits q (e-r)) (hs 1) := by
  apply congrArg₂ Tapes.mk
  · funext i; fin_cases i <;> rfl
  · funext i; fin_cases i
    · rfl
    · rfl
    · rfl
    · rfl
    · rfl
    · rfl

private theorem gap_active_output (q P G B e r : ℕ) (hs : Fin 5 → List Bool) :
    Placement.active gapPlacement (state (a := a) q P G B e r 5 hs) = BoundedProductDescriptor.output (q := a) (FixedBasePowerStep.bits q (e-r)) (hs 1) G (q^(e-r)) := by
  apply congrArg₂ Tapes.mk
  · funext i; fin_cases i <;> rfl
  · funext i; fin_cases i
    · rfl
    · rfl
    · rfl
    · rfl
    · rfl
    · rfl

private theorem gap_extra (q P G B e r : ℕ) (hs : Fin 5 → List Bool) :
    Placement.extra gapPlacement (state (a := a) q P G B e r 4 hs) = Placement.extra gapPlacement (state (a := a) q P G B e r 5 hs) := by
  apply congrArg₂ Tapes.mk <;> funext i <;> fin_cases i <;> rfl

private theorem suffix_active_input (q P G B e r : ℕ) (hs : Fin 5 → List Bool) :
    Placement.active suffixPlacement (state (a := a) q P G B e r 5 hs) = BoundedProductDescriptor.input (q := a) (FixedBasePowerStep.bits q (e-r)) (hs 2) := by
  apply congrArg₂ Tapes.mk
  · funext i; fin_cases i <;> rfl
  · funext i; fin_cases i
    · rfl
    · rfl
    · rfl
    · rfl
    · rfl
    · rfl

private theorem suffix_active_output (q P G B e r : ℕ) (hs : Fin 5 → List Bool) :
    Placement.active suffixPlacement (state (a := a) q P G B e r 6 hs) = BoundedProductDescriptor.output (q := a) (FixedBasePowerStep.bits q (e-r)) (hs 2) B (q^(e-r)) := by
  apply congrArg₂ Tapes.mk
  · funext i; fin_cases i <;> rfl
  · funext i; fin_cases i
    · rfl
    · rfl
    · rfl
    · rfl
    · rfl
    · rfl

private theorem suffix_extra (q P G B e r : ℕ) (hs : Fin 5 → List Bool) :
    Placement.extra suffixPlacement (state (a := a) q P G B e r 5 hs) = Placement.extra suffixPlacement (state (a := a) q P G B e r 6 hs) := by
  apply congrArg₂ Tapes.mk <;> funext i <;> fin_cases i <;> rfl

private theorem difference_hoare (q P G B e r : ℕ) (_hq : 2 ≤ q) (hr : r ≤ e)
    (hs : Fin 5 → List Bool) (hv : ∀ i, Counter.value (hs i) = originalValues P G B e r i)
    (hc : ∀ i, GrowingCounterData.Canonical (hs i)) :
    HoareTime (differenceProgram (a := a)) (fun v => v = input hs)
      (fun v => v = state q P G B e r 1 hs) (6*e+27) := by
  have hx : Counter.value (hs 3) = e := hv 3
  have hy : Counter.value (hs 4) = r := hv 4
  have h := BinaryDescriptorDifference.difference_linear (a := a) (hs 3) (hs 4)
    (by rw [hx,hy]; exact hr) (hc 3) (hc 4)
  rw [hx,hy] at h
  apply placed_exact differencePlacement (input hs) (state q P G B e r 1 hs)
    (BinaryDescriptorDifference.input (hs 3) (hs 4)) (BinaryDescriptorDifference.output (hs 3) (hs 4) (RecursiveChildQuotientsConstant.bits (e-r))) ?_ ?_ ?_ h
  · exact difference_active_input (a := a) q P G B e r hs
  · exact difference_active_output (a := a) q P G B e r hs
  · exact difference_extra (a := a) q P G B e r hs

private theorem high_hoare (q P G B e r : ℕ) (hq : 2 ≤ q) (_hr : r ≤ e)
    (hs : Fin 5 → List Bool) (hv : ∀ i, Counter.value (hs i) = originalValues P G B e r i)
    (hc : ∀ i, GrowingCounterData.Canonical (hs i)) :
    HoareTime (highProgram (a := a) q) (fun v => v = state q P G B e r 1 hs)
      (fun v => v = state q P G B e r 2 hs) (FixedBasePowerDescriptor.constant q*q^r) := by
  have h := FixedBasePowerDescriptor.constructs_linear (q := a) q r hq (hs 4)
    (hv 4) (hc 4)
  apply placed_exact highPlacement (state q P G B e r 1 hs) (state q P G B e r 2 hs)
    (FixedBasePowerDescriptor.input (hs 4)) (FixedBasePowerDescriptor.output q r (hs 4)) ?_ ?_ ?_ h
  · exact high_active_input (a := a) q P G B e r hs
  · exact high_active_output (a := a) q P G B e r hs
  · exact high_extra (a := a) q P G B e r hs

private theorem low_hoare (q P G B e r : ℕ) (hq : 2 ≤ q) (_hr : r ≤ e)
    (hs : Fin 5 → List Bool) (_hv : ∀ i, Counter.value (hs i) = originalValues P G B e r i)
    (_hc : ∀ i, GrowingCounterData.Canonical (hs i)) :
    HoareTime (lowProgram (a := a) q) (fun v => v = state q P G B e r 2 hs)
      (fun v => v = state q P G B e r 3 hs) (FixedBasePowerDescriptor.constant q*q^(e-r)) := by
  have h := FixedBasePowerDescriptor.constructs_linear (q := a) q (e-r) hq (RecursiveChildQuotientsConstant.bits (e-r))
    (RecursiveChildQuotientsConstant.bits_value _) (RecursiveChildQuotientsConstant.bits_canonical _)
  apply placed_exact lowPlacement (state q P G B e r 2 hs) (state q P G B e r 3 hs)
    (FixedBasePowerDescriptor.input (RecursiveChildQuotientsConstant.bits (e-r))) (FixedBasePowerDescriptor.output q (e-r) (RecursiveChildQuotientsConstant.bits (e-r))) ?_ ?_ ?_ h
  · exact low_active_input (a := a) q P G B e r hs
  · exact low_active_output (a := a) q P G B e r hs
  · exact low_extra (a := a) q P G B e r hs

private theorem prefix_hoare (q P G B e r : ℕ) (hq : 2 ≤ q) (_hr : r ≤ e)
    (hs : Fin 5 → List Bool) (hv : ∀ i, Counter.value (hs i) = originalValues P G B e r i)
    (hc : ∀ i, GrowingCounterData.Canonical (hs i)) :
    HoareTime (prefixProgram (a := a)) (fun v => v = state q P G B e r 3 hs)
      (fun v => v = state q P G B e r 4 hs) (53*(P*q^r)+28) := by
  have hn : Counter.value (hs 0) = P := hv 0
  have hw := GrowingCounterData.canonical_width (FixedBasePowerStep.bits q r)
    (FixedBasePowerStep.bits_canonical q r)
  rw [FixedBasePowerStep.bits_value] at hw
  have hh := GrowingCounterData.canonical_width (hs 0) (hc 0)
  rw [hn] at hh
  have h := BoundedProductDescriptor.construct_hoare (q := a) (FixedBasePowerStep.bits q r)
    (hs 0) P (q^r) P (pow_pos (by omega : 0 < q) _) (FixedBasePowerStep.bits_value _ _) hn le_rfl
    (hw.trans (Nat.add_le_add_right (Nat.log2_le_self _) 1))
    (hh.trans (Nat.add_le_add_right (Nat.log2_le_self _) 1))
  apply placed_exact prefixPlacement (state q P G B e r 3 hs) (state q P G B e r 4 hs)
    (BoundedProductDescriptor.input (FixedBasePowerStep.bits q r) (hs 0)) (BoundedProductDescriptor.output (FixedBasePowerStep.bits q r) (hs 0) P (q^r)) ?_ ?_ ?_ h
  · exact prefix_active_input (a := a) q P G B e r hs
  · exact prefix_active_output (a := a) q P G B e r hs
  · exact prefix_extra (a := a) q P G B e r hs

private theorem gap_hoare (q P G B e r : ℕ) (hq : 2 ≤ q) (_hr : r ≤ e)
    (hs : Fin 5 → List Bool) (hv : ∀ i, Counter.value (hs i) = originalValues P G B e r i)
    (hc : ∀ i, GrowingCounterData.Canonical (hs i)) :
    HoareTime (gapProgram (a := a)) (fun v => v = state q P G B e r 4 hs)
      (fun v => v = state q P G B e r 5 hs) (53*(G*q^(e-r))+28) := by
  have hn : Counter.value (hs 1) = G := hv 1
  have hw := GrowingCounterData.canonical_width (FixedBasePowerStep.bits q (e-r))
    (FixedBasePowerStep.bits_canonical q (e-r))
  rw [FixedBasePowerStep.bits_value] at hw
  have hh := GrowingCounterData.canonical_width (hs 1) (hc 1)
  rw [hn] at hh
  have h := BoundedProductDescriptor.construct_hoare (q := a) (FixedBasePowerStep.bits q (e-r))
    (hs 1) G (q^(e-r)) G (pow_pos (by omega : 0 < q) _) (FixedBasePowerStep.bits_value _ _) hn le_rfl
    (hw.trans (Nat.add_le_add_right (Nat.log2_le_self _) 1))
    (hh.trans (Nat.add_le_add_right (Nat.log2_le_self _) 1))
  apply placed_exact gapPlacement (state q P G B e r 4 hs) (state q P G B e r 5 hs)
    (BoundedProductDescriptor.input (FixedBasePowerStep.bits q (e-r)) (hs 1)) (BoundedProductDescriptor.output (FixedBasePowerStep.bits q (e-r)) (hs 1) G (q^(e-r))) ?_ ?_ ?_ h
  · exact gap_active_input (a := a) q P G B e r hs
  · exact gap_active_output (a := a) q P G B e r hs
  · exact gap_extra (a := a) q P G B e r hs

private theorem suffix_hoare (q P G B e r : ℕ) (hq : 2 ≤ q) (_hr : r ≤ e)
    (hs : Fin 5 → List Bool) (hv : ∀ i, Counter.value (hs i) = originalValues P G B e r i)
    (hc : ∀ i, GrowingCounterData.Canonical (hs i)) :
    HoareTime (suffixProgram (a := a)) (fun v => v = state q P G B e r 5 hs)
      (fun v => v = state q P G B e r 6 hs) (53*(B*q^(e-r))+28) := by
  have hn : Counter.value (hs 2) = B := hv 2
  have hw := GrowingCounterData.canonical_width (FixedBasePowerStep.bits q (e-r))
    (FixedBasePowerStep.bits_canonical q (e-r))
  rw [FixedBasePowerStep.bits_value] at hw
  have hh := GrowingCounterData.canonical_width (hs 2) (hc 2)
  rw [hn] at hh
  have h := BoundedProductDescriptor.construct_hoare (q := a) (FixedBasePowerStep.bits q (e-r))
    (hs 2) B (q^(e-r)) B (pow_pos (by omega : 0 < q) _) (FixedBasePowerStep.bits_value _ _) hn le_rfl
    (hw.trans (Nat.add_le_add_right (Nat.log2_le_self _) 1))
    (hh.trans (Nat.add_le_add_right (Nat.log2_le_self _) 1))
  apply placed_exact suffixPlacement (state q P G B e r 5 hs) (state q P G B e r 6 hs)
    (BoundedProductDescriptor.input (FixedBasePowerStep.bits q (e-r)) (hs 2)) (BoundedProductDescriptor.output (FixedBasePowerStep.bits q (e-r)) (hs 2) B (q^(e-r))) ?_ ?_ ?_ h
  · exact suffix_active_input (a := a) q P G B e r hs
  · exact suffix_active_output (a := a) q P G B e r hs
  · exact suffix_extra (a := a) q P G B e r hs

def cost (q P G B e r : ℕ) :=
  6*e+27+FixedBasePowerDescriptor.constant q*q^r+
    FixedBasePowerDescriptor.constant q*q^(e-r)+53*(P*q^r)+28+
    (53*(G*q^(e-r))+28)+(53*(B*q^(e-r))+28)+5

/-- All six generated controls arise from physical subprograms, while the
five original headers survive and every arithmetic tape returns blank. -/
theorem construct_hoare (q P G B e r : ℕ) (hq : 2 ≤ q) (hr : r ≤ e)
    (hs : Fin 5 → List Bool) (hv : ∀ i, Counter.value (hs i) = originalValues P G B e r i)
    (hc : ∀ i, GrowingCounterData.Canonical (hs i)) :
    HoareTime (program (a := a) q) (fun v => v = input hs)
      (fun v => v = output q P G B e r hs) (cost q P G B e r) := by
  have h := (((((difference_hoare (a := a) q P G B e r hq hr hs hv hc).seq
    (high_hoare (a := a) q P G B e r hq hr hs hv hc)).seq
    (low_hoare (a := a) q P G B e r hq hr hs hv hc)).seq
    (prefix_hoare (a := a) q P G B e r hq hr hs hv hc)).seq
    (gap_hoare (a := a) q P G B e r hq hr hs hv hc)).seq
    (suffix_hoare (a := a) q P G B e r hq hr hs hv hc)
  exact h.consequence (fun _ h => h) (fun _ h => h) (by unfold cost; omega)

def linearConstant (q : ℕ) := 2*FixedBasePowerDescriptor.constant q+281

theorem cost_le (q P G B e r V : ℕ) (hV : 0 < V) (he : e ≤ V)
    (hvalues : ∀ i, values q P G B e r i ≤ V) :
    cost q P G B e r ≤ linearConstant q*V := by
  have hhi := Nat.mul_le_mul_left (FixedBasePowerDescriptor.constant q) (hvalues 1)
  have hlo := Nat.mul_le_mul_left (FixedBasePowerDescriptor.constant q) (hvalues 2)
  have hp : P*q^r ≤ V := hvalues 3
  have hg : G*q^(e-r) ≤ V := hvalues 4
  have hb : B*q^(e-r) ≤ V := hvalues 5
  change FixedBasePowerDescriptor.constant q*q^r ≤ FixedBasePowerDescriptor.constant q*V at hhi
  change FixedBasePowerDescriptor.constant q*q^(e-r) ≤ FixedBasePowerDescriptor.constant q*V at hlo
  unfold cost linearConstant
  simp only [Nat.add_mul,Nat.mul_assoc]
  omega

def dataVolume (q P G B e : ℕ) := P*G*B*q^(2*e)

private theorem width_power (q e : ℕ) (hq : 2 ≤ q) : e+1 ≤ q^e := by
  induction e with
  | zero => simp
  | succ e ih =>
    rw [pow_succ]
    have hp : 0 < q^e := pow_pos (by omega) _
    nlinarith

theorem data_volume_bounds (q P G B e r : ℕ) (hq : 2 ≤ q) (hr : r ≤ e)
    (hP : 0 < P) (hG : 0 < G) (hB : 0 < B) :
    0 < dataVolume q P G B e ∧ e ≤ dataVolume q P G B e ∧
      ∀ i, values q P G B e r i ≤ dataVolume q P G B e := by
  have houter : 0 < P*G*B := Nat.mul_pos (Nat.mul_pos hP hG) hB
  have hpow : 0 < q^(2*e) := pow_pos (by omega) _
  have hbase : q^(2*e) ≤ dataVolume q P G B e := by
    exact Nat.le_mul_of_pos_left _ houter
  have hepow := width_power q e hq
  have hep : q^e ≤ q^(2*e) := Nat.pow_le_pow_right (by omega : 0 < q) (by omega)
  have hp : q^r ≤ q^(2*e) := Nat.pow_le_pow_right (by omega : 0 < q) (by omega)
  have hl : q^(e-r) ≤ q^(2*e) := Nat.pow_le_pow_right (by omega : 0 < q) (by omega)
  have hPouter : P ≤ P*G*B := (Nat.le_mul_of_pos_right _ hG).trans (Nat.le_mul_of_pos_right _ hB)
  have hGouter : G ≤ P*G*B := by
    have h := (Nat.le_mul_of_pos_right G hP).trans (Nat.le_mul_of_pos_right _ hB)
    simpa only [Nat.mul_comm G P] using h
  have hBouter : B ≤ P*G*B := by
    have h := (Nat.le_mul_of_pos_right B hP).trans (Nat.le_mul_of_pos_right _ hG)
    convert h using 1; ring
  refine ⟨Nat.mul_pos houter hpow,by omega,?_⟩
  intro i
  fin_cases i
  · change e-r ≤ _; omega
  · exact hp.trans hbase
  · exact hl.trans hbase
  · exact Nat.mul_le_mul hPouter hp
  · exact Nat.mul_le_mul hGouter hl
  · exact Nat.mul_le_mul hBouter hl

theorem construct_linear (q P G B e r : ℕ) (hq : 2 ≤ q) (hr : r ≤ e)
    (hP : 0 < P) (hG : 0 < G) (hB : 0 < B)
    (hs : Fin 5 → List Bool) (hv : ∀ i, Counter.value (hs i) = originalValues P G B e r i)
    (hc : ∀ i, GrowingCounterData.Canonical (hs i)) :
    HoareTime (program (a := a) q) (fun v => v = input hs)
      (fun v => v = output q P G B e r hs) (linearConstant q*dataVolume q P G B e) := by
  have hb := data_volume_bounds q P G B e r hq hr hP hG hB
  exact (construct_hoare (a := a) q P G B e r hq hr hs hv hc).consequence
    (fun _ h => h) (fun _ h => h) (cost_le q P G B e r _ hb.1 hb.2.1 hb.2.2)


end
end IntegerMultBounds.Machine.ArbitraryWidthHighDimensions
