import IntegerMultBounds.Machine.BinaryDescriptorQueueRead
import IntegerMultBounds.Machine.CompactComplexRootDigits

/-! Paid rewind of a forward binary-field queue from its actual end cursor.
The blank cell immediately before its first field is the physical sentinel;
all queue symbols and the trailing blank are retained exactly. -/
namespace IntegerMultBounds.Machine.BinaryDescriptorQueueRewind
noncomputable section
open MarkedWordCleanup (one)
variable {a : ℕ}

def moveProgram (dir : Move) : Program 1 2 a :=
  DescriptorStackControl.once (by decide) (fun sy i => (sy i,dir))
private theorem move_runs (f : ℤ → Fin (a+4)) (p : ℤ) (dir : Move) :
    HoareTime (moveProgram dir) (fun v => v=one f p)
      (fun v => v=one f (p+dir.offset)) 1 := by
  apply (DescriptorStackControl.once_hoare (by decide) _ (one f p)).consequence
    (fun _ h => h) _ le_rfl
  rintro v rfl
  apply congrArg₂ Tapes.mk
  · rfl
  · funext i z
    by_cases hz : z=p <;> simp [one,hz]

def program : Program 1 5 a :=
  seq (seq (moveProgram .left) (Rewind.program blank)) (moveProgram .right)

/-- No list length enters the machine: the retained blank at zero stops it. -/
theorem runs (xs : List (Fin (a+4))) (hn : ∀ x∈xs, x≠blank) :
    HoareTime program
      (fun v => v=one (putWord (fun _ => blank) 1 xs) (1+xs.length))
      (fun v => v=one (putWord (fun _ => blank) 1 xs) 1) (xs.length+4) := by
  let f := putWord (fun _ => blank) 1 xs
  have hl := move_runs (a := a) f (1+xs.length) .left
  have hr := Rewind.rewind_hoare (blank : Fin (a+4)) f xs.length xs.length
    (by
      intro j hj
      have hm := ReturnOrigin.putWord_mem (fun _ => blank) 1 xs (xs.length-j)
        (by constructor <;> omega)
      exact hn _ hm)
    (by rw [sub_self]; exact putWord_outside _ _ _ _ (Or.inl (by omega)))
  simp only [Move.offset,show (1 : ℤ)+xs.length+(-1)=xs.length by omega] at hl
  simp only [Rewind.cfg,Config.tapes,sub_self] at hr
  have hh := move_runs (a := a) f 0 .right
  simp only [Move.offset,zero_add] at hh
  exact ((hl.seq hr).seq hh).consequence (fun _ h => h) (fun _ h => h) (by omega)

/-- The queue generated by the root-digit machine has no internal blanks,
including empty-bit fields for zero digits. -/
theorem fields_nonblank (ds : List ℕ) :
    ∀ x∈CompactComplexRootDigits.fields (a := a) ds, x≠blank := by
  intro x hx
  obtain ⟨n,_,hn⟩ := List.mem_flatMap.mp hx
  rcases List.mem_append.mp hn with hb | hs
  · obtain ⟨b,_,rfl⟩ := List.mem_map.mp hb
    cases b <;> simp [bitSymbol,blank,Fin.ext_iff]
  · have hx : x=separator := by simpa using hs
    rw [hx]
    simp [separator,blank,Fin.ext_iff]

theorem fields_runs (ds : List ℕ) :
    HoareTime (program (a := a))
      (fun v => v=one (putWord (fun _ => blank) 1 (CompactComplexRootDigits.fields ds))
        (1+(CompactComplexRootDigits.fields (a := a) ds).length))
      (fun v => v=one (putWord (fun _ => blank) 1 (CompactComplexRootDigits.fields ds)) 1)
      ((CompactComplexRootDigits.fields (a := a) ds).length+4) :=
  runs _ (fields_nonblank ds)

end
end IntegerMultBounds.Machine.BinaryDescriptorQueueRewind
