import IntegerMultBounds.Machine.CompactNativeConjugatedSharedCaller
import IntegerMultBounds.Machine.CompactNativeRoleChildHeadersPorts
import IntegerMultBounds.Machine.NativePolynomialStageHeaders

/-! Actual numeric43 role headers supply the full native conjugated caller.
The alphabet change is an explicit symbol encoding from six symbols into the
prime alphabet. The selected role remains the physically shared source. -/
namespace IntegerMultBounds.Machine.CompactNativeRoleConjugatedPorts
noncomputable section
open CompactGadgetReservationShape (Shape)
open ActivePrefixStageParameters (Stage)
open CompactNativeRoleSourcePorts (callerTapes external)
open CompactNativeRoleChildHeadersPorts (slot)
open Networks.Shared50ModularControl (prime)
variable {t c : ℕ}

def encoding : Alphabet.Encoding 2 prime := SymbolTriplePlaced.encoding ActivePrefixStageNative.ha
def focus (t c : ℕ) (i : Fin 14) : Fin (callerTapes t c) :=
  Fin.addCases (fun i : Fin 13 => slot t c (Fin.castAdd 30 i))
    (fun _ : Fin 1 => slot t c 17) i
def selected (t : ℕ) (j : Fin c) : Fin (callerTapes t c) := Fin.natAdd (t+43) j

theorem map_binary (bs : List Bool) :
    SymbolTriplePlaced.mapTape ActivePrefixStageNative.ha (RadixZeroFill.encodedBinary (q:=2) bs)=
      RadixZeroFill.encodedBinary (q:=prime) bs := by
  funext z
  apply Fin.ext
  rfl

theorem numeric_headers (old : Tapes t 2) (ht : 43<t)
    (st : ActiveRepairRankHeadersCommands.State) (payload : Tapes (1+c) 2)
    {s : Shape} (d : ActivePrefixStageFullData.Inputs s) (ell : ℕ)
    (h13 : ∀ i,st (Fin.castAdd 15 i)=some (ActivePrefixStageHeadersData.originalValues d.stage d.rows i))
    (hell : st 17=some ell) (i : Fin 14) :
    (Alphabet.mapTapes encoding (external old ht st payload)).tape (focus t c i)=
      RadixZeroFill.encodedBinary (AllAxisPhaseOriginalScalar.words d ell i) ∧
    (Alphabet.mapTapes encoding (external old ht st payload)).head (focus t c i)=1 := by
  induction i using Fin.addCases (m:=13) (n:=1) with
  | left i =>
    simp only [focus,Fin.addCases_left,AllAxisPhaseOriginalScalar.words]
    have hv : (external old ht st payload).tape (slot t c (Fin.castAdd 30 i))=
        RadixZeroFill.encodedBinary (q:=2) (AllAxisPhaseOriginalPorts.words d i) ∧
        (external old ht st payload).head (slot t c (Fin.castAdd 30 i))=1 := by
      have he : Fin.castAdd 30 i=Fin.castAdd 15 (Fin.castAdd 15 i) := Fin.ext rfl
      simp only [external,slot,Tapes.append,
        ActiveRepairRankHeadersCommands.bank,CleanSubbank.bank,he]
      simp [ActiveRepairRankHeadersCommands.caller,h13,AllAxisPhaseOriginalPorts.words]
    constructor
    · change SymbolTriplePlaced.mapTape ActivePrefixStageNative.ha
        ((external old ht st payload).tape (slot t c (Fin.castAdd 30 i)))=_
      rw [hv.1,map_binary]
    · exact hv.2
  | right i =>
    simp only [focus,Fin.addCases_right,AllAxisPhaseOriginalScalar.words]
    have hv : (external old ht st payload).tape (slot t c 17)=
        RadixZeroFill.encodedBinary (q:=2) (RecursiveChildQuotientsConstant.bits ell) ∧
        (external old ht st payload).head (slot t c 17)=1 := by
      simp only [external,slot,Tapes.append,
        ActiveRepairRankHeadersCommands.bank,CleanSubbank.bank]
      simp only [Function.comp_apply,Fin.addCases_left,Fin.addCases_right]
      change (ActiveRepairRankHeadersCommands.caller (a:=2) st).tape 17=_ ∧
        (ActiveRepairRankHeadersCommands.caller (a:=2) st).head 17=1
      simp [ActiveRepairRankHeadersCommands.caller,hell]
    constructor
    · change SymbolTriplePlaced.mapTape ActivePrefixStageNative.ha ((external old ht st payload).tape (slot t c 17))=_
      rw [hv.1,map_binary]
    · exact hv.2

/-- The header words are those physically generated by the codec adapter;
the saved original payload at26 is framed rather than copied as metadata. -/
theorem prepared_headers (old : Tapes t 2) (ht : 43<t) (payload : Tapes (1+c) 2)
    {s : Shape} (v : Stage s) (rows ell p : ℕ)
    (hG : 1≤s.guard) (hGK : s.guard+1≤s.chunk) (hr : 0<rows) (i : Fin 14) :
    let st := NativePolynomialStageHeaders.prepared s rows ell p v.rho v.left v.f v.slots v.right v.source.val v.target.val
    let d := NativePolynomialStageShape.inputs v rows ell p hG hGK hr
    (Alphabet.mapTapes encoding (external old ht st payload)).tape (focus t c i)=
      RadixZeroFill.encodedBinary (AllAxisPhaseOriginalScalar.words d ell i) ∧
    (Alphabet.mapTapes encoding (external old ht st payload)).head (focus t c i)=1 := by
  apply numeric_headers
  · exact NativePolynomialStageHeaders.prepared_original v rows ell p
  · exact (NativePolynomialStageHeaders.prepared_immutable s rows ell p v.rho v.left v.f v.slots v.right v.source.val v.target.val).1

/-- The selected native role source uses the same literal six-symbol encoding
as the native polynomial caller, with its physical head retained. -/
theorem selected_source (old : Tapes t 2) (ht : 43<t)
    (st : ActiveRepairRankHeadersCommands.State) (payload : Tapes (1+c) 2) (j : Fin c) :
    (Alphabet.mapTapes encoding (external old ht st payload)).tape (selected t j)=
      SymbolTriplePlaced.mapTape ActivePrefixStageNative.ha (payload.tape ⟨j.val+1,by omega⟩) ∧
    (Alphabet.mapTapes encoding (external old ht st payload)).head (selected t j)=
      payload.head ⟨j.val+1,by omega⟩ := by
  simp only [Alphabet.mapTapes,external,selected,Tapes.append,Fin.addCases_right,
    CompactNativeRoleSourcePorts.roles]
  constructor
  · rfl
  · trivial

def program {q : ℕ} (P : Program ActivePrefixStageNative.tapes q prime)
    (t c : ℕ) (j : Fin c) (order : ActivePrefixStageHeadersData.Order)
    (pc : Fin CompactAllAxisPhaseDispatch.count) :=
  CompactNativeConjugatedSharedCaller.program P (focus t c) (selected t j) order pc

/-- Actual generated role metadata and the actual selected six-symbol source
execute the physical prime-side copy, native conjugation and cleanup caller. -/
theorem prepared_runs {q B phaseCost : ℕ} (P : Program ActivePrefixStageNative.tapes q prime)
    (old : Tapes t 2) (ht : 43<t) (payload : Tapes (1+c) 2) (j : Fin c)
    {s : Shape} (v : Stage s) (rows ell p : ℕ)
    (hG : 1≤s.guard) (hGK : s.guard+1≤s.chunk) (hr : 0<rows)
    (order : ActivePrefixStageHeadersData.Order) (pc : Fin CompactAllAxisPhaseDispatch.count)
    (xs ys : ActivePrefixStageNativeRows.Rows (NativePolynomialStageShape.inputs v rows ell p hG hGK hr) B)
    (hword : payload.tape ⟨j.val+1,by omega⟩=
      SymbolTripleClean.word (List.ofFn (ActivePrefixStageNativeRows.flat xs)))
    (hhead : payload.head ⟨j.val+1,by omega⟩=0)
    (hphase : HoareTime (CompactNativeConjugatedPhase.program P order pc)
      (fun z => z=CompactNativeConjugatedPhase.bank (NativePolynomialStageShape.inputs v rows ell p hG hGK hr) ell xs)
      (fun z => z=CompactNativeConjugatedPhase.bank (NativePolynomialStageShape.inputs v rows ell p hG hGK hr) ell ys) phaseCost) :
    let d := NativePolynomialStageShape.inputs v rows ell p hG hGK hr
    let st := NativePolynomialStageHeaders.prepared s rows ell p v.rho v.left v.f v.slots v.right v.source.val v.target.val
    let caller := Alphabet.mapTapes encoding (external old ht st payload)
    HoareTime (program P t c j order pc)
      (fun z => z=caller.append (FixedHeaderBankCopy.empty CompactNativeConjugatedHeaderBank.tapes))
      (fun z => z=(SharedPlacementAlphabet.setTape caller (selected t j)
        ((CompactNativeConjugatedPhase.bank d ell ys).tape CompactNativeConjugatedHeaderBank.source)
        ((CompactNativeConjugatedPhase.bank d ell ys).head CompactNativeConjugatedHeaderBank.source)).append
          (FixedHeaderBankCopy.empty CompactNativeConjugatedHeaderBank.tapes))
      (CompactNativeConjugatedSharedCaller.cost (callerTapes t c) d ell phaseCost) := by
  dsimp only
  apply CompactNativeConjugatedSharedCaller.runs P (focus t c) (selected t j) order pc
  · intro i; exact (prepared_headers old ht payload v rows ell p hG hGK hr i).1
  · intro i; exact (prepared_headers old ht payload v rows ell p hG hGK hr i).2
  · rw [(selected_source old ht _ payload j).1,
      (CompactNativeConjugatedHeaderBank.bank_source _ xs ell).1,hword]
    rfl
  · rw [(selected_source old ht _ payload j).2,
      (CompactNativeConjugatedHeaderBank.bank_source _ xs ell).2,hhead]
  · exact hphase

end
end IntegerMultBounds.Machine.CompactNativeRoleConjugatedPorts
